#!/bin/bash
#
# description: Ventrilo init script
# processname: ventrilo_srv
# chkconfig: 234 20 80
#

#VENTRILO_HOME is the location of the configuration files of this instance of Ventrilo
export VENTRILO_HOME=/home/ventrilo/ventsrv

#VENTRILO_USER is the default user of Ventrilo
export VENTRILO_USER=ventrilo

#VENTRILO_USAGE is the message if this script is called without any options
VENTRILO_USAGE="Usage: $0 {\e[00;32mstart\e[00m|\e[00;31mstop\e[00m|\e[00;31mkill\e[00m|\e[00;32mstatus\e[00m|\e[00;31mrestart\e[00m}"

ventrilo_pid() {
	echo `ps -fe | grep ventrilo_srv | grep -v grep | tr -s " "|cut -d" " -f2`
}

start() {
    pid=$(ventrilo_pid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mVentrilo is already running (pid: $pid)\e[00m"
    else
        # Start Ventrilo
        echo -e "\e[00;32mStarting Ventrilo\e[00m"
        if [ `user_exists $VENTRILO_USER` = "1" ]
        then
            /bin/su $VENTRILO_USER -c "$VENTRILO_HOME/ventrilo_srv -d"
        else
            echo -e "\e[00;31mVentrilo user $VENTRILO_USER does not exist. Exiting...\e[00m"
        fi
        status
    fi
    return 0
}

status(){
    pid=$(ventrilo_pid)
    if [ -n "$pid" ]
    then
		echo -e "\e[00;32mVentrilo is running with pid: $pid\e[00m"
		if [ `user_exists $VENTRILO_USER` = "1" ]
        then
            /bin/su $VENTRILO_USER -c "$VENTRILO_HOME/ventrilo_status -c1 -t127.0.0.1"
        fi
    else
        echo -e "\e[00;31mVentrilo is not running\e[00m"
        return 3
    fi
}

terminate() {
    echo -e "\e[00;31mTerminating Ventrilo\e[00m"
    kill -9 $(ventrilo_pid)
}

stop() {
    pid=$(ventrilo_pid)
    if [ -n "$pid" ]
    then
        terminate
    else
        echo -e "\e[00;31mVentrilo is not running\e[00m"
    fi

    return 0
}

user_exists(){
    if id -u $1 >/dev/null 2>&1; then
		echo "1"
    else
        echo "0"
    fi
}

case $1 in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
    status)
        status
        exit $?
    ;;
    kill)
        terminate
    ;;
    *)
        echo -e $VENTRILO_USAGE
    ;;
esac
exit 0
